import AppProvider from '@/contexts/AppProvider'
import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Teste Login',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-Br">
      <body>
        <div className={"grid grid-cols-18 gap-x-2 max-lg:gap-x-1 min-h-screen auto-rows-max " + inter.className}>
          <AppProvider>
            {children}
          </AppProvider>
        </div>
      </body>
    </html>
  )
}
